version: 2

builds:
  - id: vanityssh
    binary: vanityssh
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

nfpms:
  - package_name: vanityssh
    vendor: danielewood
    homepage: https://github.com/danielewood/vanityssh-go
    maintainer: danielewood
    description: Generate ED25519 SSH keys with vanity public keys
    license: MIT
    formats:
      - deb

checksum:
  name_template: checksums.txt
