repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: no-commit-to-branch
        args: [--branch, main]

  - repo: https://github.com/sensiblebit/.github
    rev: ad268a51ad8ce705d2e1d4010700a334ea3ea3f9
    hooks:
      - id: branch-name
      - id: commit-message
        stages: [commit-msg]
      - id: goimports
      - id: go-fix
      - id: go-vet
      - id: go-build
      - id: go-test

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.48.0
    hooks:
      - id: markdownlint
